function sendEmail(expLog)
% sendEmail function can send email by Matlab.
% email sender
sendMailAddress = 'deyunlyu@gmail.com';
% app-specific password 
password = 'ctmktibfuxcanswd';  
% gmail SMTP server
smtpServer = 'smtp.gmail.com';
% SMTP port
smtpPort = '587';
% configure SMTP server and account information
setpref('Internet','E_mail',sendMailAddress);
setpref('Internet','SMTP_Server', smtpServer);
setpref('Internet','SMTP_Username',sendMailAddress);
setpref('Internet','SMTP_Password',password);
props = java.lang.System.getProperties;
props.setProperty( 'mail.smtp.auth', 'true');
props.setProperty( 'mail.smtp.user', sendMailAddress);
props.setProperty( 'mail.smtp.password', password);
props.setProperty( 'mail.smtp.host', smtpServer);
props.setProperty( 'mail.smtp.port', smtpPort);
props.setProperty( 'mail.smtp.starttls.enable', 'true');

%% send email
% subject 
subject = 'Generated by the AutoPatch';
% email content
content = 'Code execution complete!';
receiveMailAddress1='lyudeyun@gmail.com';
receiveMailAddress2 = 'lyu.deyun.107@s.kyushu-u.ac.jp';
sendmail(receiveMailAddress1,subject,content, expLog);
sendmail(receiveMailAddress2,subject,content, expLog);
end